apiVersion: v1
kind: Secret
metadata:
  name: myrepo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: oci://demo.goharbor.io/vision
  name: myrepo
  type: helm